version: '3.1'

services:
  go-simple-restful:
    restart: always
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - 8005:8005
    links:
      - mysql
    environment:
      - "GO_SIMPLE_RESTFUL_DBPORT=3306"
      - "GO_SIMPLE_RESTFUL_DBHOST=mysql"
      - "GO_SIMPLE_RESTFUL_DBUSER=root"
      - "GO_SIMPLE_RESTFUL_DBNAME=go_simple_RESTful"
      - "GO_SIMPLE_RESTFUL_DBPASSWORD=roottest"
  
  mysql:
    image: mysql:5.7.19
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: roottest
      MYSQL_DATABASE: go_simple_RESTful
